# Generated by Django 5.2.1 on 2025-06-04 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('sentiment', models.CharField(max_length=50)),
                ('sentiment_score', models.FloatField()),
                ('entities', models.JSONField()),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary', models.TextField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
